### ISSUE TITLE
Where can I find the Temporal Shift Setting&Exposure Shift Setting dataset？

### ISSUE THREAD

**Issue by Andy3117006664** [WANGBohaO-jpg/DR-GNN#1]
![微信图片_20240603205611](https://github.com/WANGBohaO-jpg/DR-GNN/assets/80371503/b418fd4e-b7a5-4ebd-8f22-fde4e7239b56)

**Comment by WANGBohaO-jpg** [comment]
Thank you for your interest in our work. I have uploaded the datasets used in the implementation of the paper to the repository. You can find it in the OOD_data.
